### ISSUE TITLE
unable to badge app on iOS

### ISSUE THREAD

**Issue by oiledCode** [HazAT/badge#34] opened 2016-11-23 15:33 UTC
Hello, 
I've tried to integrate your gem to badge my app icon with no luck so far.
Everytime I launch the badge command I receive the following error : 

![screen shot 2016-11-23 at 16 31 31](https://cloud.githubusercontent.com/assets/580402/20567785/58c277f2-b19a-11e6-8098-863dbbd1b1cd.png)

My env : OSX 10.11.5, imagemagick gem installed
Thanks in advance for your help

**Comment by dcordero** [comment] 2016-11-23 16:24
@oiledCode could you please sent the logs when adding the option `--verbose` to badge?

**Comment by oiledCode** [comment] 2016-11-23 17:31
@dcordero 
<img width="1540" alt="screen shot 2016-11-23 at 18 25 21" src="https://cloud.githubusercontent.com/assets/580402/20572094/4f57b1d6-b1aa-11e6-916b-30b404ca82e5.png">

What I don't understand in the output is the filename badge is looking for. For example my filename is AppIcon-40@2x.png and badge look for AppIcon-40@2x.png[0]. 

So it seems to me that the index of the file in the array, produced by Dir.glob(), is appended to the filename.

**Comment by dcordero** [comment] 2016-11-23 17:55
I am not able to reproduce it. Could you try the following commands to apply badge on Dash Application? We might be different environments. Otherwise a simple project reproducing the error would be really appreciated.

```
dcordero@Davids-MacBook:~/Sources$ git clone --quiet https://github.com/Kapeli/Dash-iOS.git
dcordero@Davids-MacBook:~/Sources$ cd Dash-iOS/
dcordero@Davids-MacBook:~/Sources/Dash-iOS$ badge --version
badge 0.5.1
dcordero@Davids-MacBook:~/Sources/Dash-iOS$ badge
[18:51:05]: Start adding badges...
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-60@2x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-60@3x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-72.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-72@2x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-76.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-76@2x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-83.5@2x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small-40.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small-40@2x.png'
[18:51:05]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small-40@3x.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small-50.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small@2x.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon-Small@3x.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon.png'
[18:51:06]: './Dash/Images.xcassets/AppIcon.appiconset/Icon@2x.png'
[18:51:06]: Badged \o/!
dcordero@Davids-MacBook:~/Sources/Dash-iOS$
```

**Comment by oiledCode** [comment] 2016-11-24 09:11
@dcordero 
Same result 
<img width="1571" alt="screen shot 2016-11-24 at 10 08 56" src="https://cloud.githubusercontent.com/assets/580402/20592491/1639129e-b22e-11e6-8feb-669679f8dd2e.png">

As additional info my ruby version is : 

> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

**Comment by HazAT** [comment] 2017-03-13 21:08
I will close this for now since is not reproducible

**Closed by HazAT** 2017-03-13 21:08 UTC
